title: "Nora Bendé"
email: bende.94@outlook.it
description: >- # this means to ignore newlines until "baseurl:"
  This is my portfolio website!
baseurl: "/" 
url: "https://NoraBende.github.io/" 
twitter_username: /
github_username:  NoraBende

sass:
  sass_dir: _sass

icon: /assets/img/icon.jpg
